export const productImages: { [key: string]: any } = {
  '1/pain-sandwich-ciabata': require('../assets/images/products/pain-frai/pain-sandwich-ciabata.png'),
  '3/pain-sandwich-tradition-nature-110gr': require('../assets/images/products/pain-surgele/pain-sandwich-tradition-nature-110gr.jpg'),
  '3/pain-sandwich-multi-cereales': require('../assets/images/products/pain-surgele/pain-sandwich-multi-cereales.jpg'),
  '3/ciabatta-multi-cereales': require('../assets/images/products/pain-surgele/ciabatta-multi-cereales.jpg'),
  '3/ciabatta-tradition': require('../assets/images/products/pain-surgele/ciabatta-tradition.jpg'),
  '1/pain-de-mie-nature-380g-assylor': require('../assets/images/products/pain-frai/pain-de-mie-nature-380g-assylor.png'),
  '1/pain-de-mie-complet-380g-12pcs-assylor': require('../assets/images/products/pain-frai/pain-de-mie-complet-380g-12pcs-assylor.png'),
  '1/pain-de-mie-huile-dolive': require('../assets/images/products/pain-frai/pain-de-mie-huile-dolive.png'),
  '1/pain-de-mie-aux-fibres': require('../assets/images/products/pain-frai/pain-de-mie-aux-fibres.png'),
  '1/pain-de-mie-au-lait': require('../assets/images/products/pain-frai/pain-de-mie-au-lait.png'),
  '1/pain-de-mie-cereale': require('../assets/images/products/pain-frai/pain-de-mie-cereale.png'),
  '1/pain-dor-nature-500g': require('../assets/images/products/pain-frai/pain-dor-nature-500g.png'),
  '1/pain-dor-complet-500g': require('../assets/images/products/pain-frai/pain-dor-complet-500g.png'),
  '1/pain-libanais-20cm-7pcs': require('../assets/images/products/pain-frai/pain-libanais-20cm-7pcs.png'),
  '1/pain-libanais-22cm-7pcs': require('../assets/images/products/pain-frai/pain-libanais-22cm-7pcs.png'),
  '1/pain-libanais-26-6pcs': require('../assets/images/products/pain-frai/pain-libanais-26-6pcs.png'),
  '1/pain-libanais-complet-20-5pcs': require('../assets/images/products/pain-frai/pain-libanais-complet-20-5pcs.png'),
  '1/pain-panini-gm-4pcs': require('../assets/images/products/pain-frai/pain-panini-gm-4pcs.png'),
  '1/pain-panini-2pcs': require('../assets/images/products/pain-frai/pain-panini-2pcs.png'),
  '1/pain-panini-pm-6pcs': require('../assets/images/products/pain-frai/pain-panini-pm-6pcs.png'),
  '1/pain-au-lait-210g': require('../assets/images/products/pain-frai/pain-au-lait-210g.png'),
  '1/pain-au-lait-choco-210g': require('../assets/images/products/pain-frai/pain-au-lait-choco-210g.png'),
  '1/pain-hamburger-4pcs-blanc': require('../assets/images/products/pain-frai/pain-hamburger-4pcs-blanc.png'),
  '1/pain-hamburger-kids': require('../assets/images/products/pain-frai/pain-hamburger-kids.png'),
  '1/pain-hamburger-geant-4': require('../assets/images/products/pain-frai/pain-hamburger-geant-4.png'),
  '1/pain-hamburger-geant-3': require('../assets/images/products/pain-frai/pain-hamburger-geant-3.png'),
  '1/pain-hamburger-geant-complet-4': require('../assets/images/products/pain-frai/pain-hamburger-geant-complet-4.png'),
  '1/pain-saucisse': require('../assets/images/products/pain-frai/pain-saucisse.png'),
  '1/pain-burger-8pcs-repas': require('../assets/images/products/pain-frai/pain-burger-8pcs-repas.png'),
  '1/pain-mega-nature-4': require('../assets/images/products/pain-frai/pain-mega-nature-4.png'),
  '1/pain-mega-chili-4': require('../assets/images/products/pain-frai/pain-mega-chili-4.png'),
  '1/pate-a-pizza-12': require('../assets/images/products/pain-frai/pate-a-pizza-12.png'),
  '1/pate-a-pizza-feuilletee-12': require('../assets/images/products/pain-frai/pate-a-pizza-feuilletee-12.png'),
  '1/pate-a-pizza-familiale': require('../assets/images/products/pain-frai/pate-a-pizza-familiale.png'),
  '1/pate-a-pizza-complet': require('../assets/images/products/pain-frai/pate-a-pizza-complet.png'),
  '1/pate-a-pizza-oignon': require('../assets/images/products/pain-frai/pate-a-pizza-oignon.png'),
  '1/pate-a-pizza-chili': require('../assets/images/products/pain-frai/pate-a-pizza-chili.png'),
  '1/pate-a-pizza-semoule': require('../assets/images/products/pain-frai/pate-a-pizza-semoule.png'),
  '1/pate-a-pizza-olive': require('../assets/images/products/pain-frai/pate-a-pizza-olive.png'),
  '1/pate-a-pizza-feuilletee': require('../assets/images/products/pain-frai/pate-a-pizza-feuilletee.png'),
  '1/traiteur-familiale-5pcs': require('../assets/images/products/pain-frai/traiteur-familiale-5pcs.png'),
  '1/traiteur-moyen-5pcs': require('../assets/images/products/pain-frai/traiteur-moyen-5pcs.png'),
  '1/chapelure-nature-250g': require('../assets/images/products/pain-frai/chapelure-nature-250g.png'),
  '1/chapelure-poulet-250g': require('../assets/images/products/pain-frai/chapelure-poulet-250g.png'),
  '1/tortilla-standard-7pcs': require('../assets/images/products/pain-frai/tortilla-standard-7pcs.png'),
  '1/tortilla-maxi': require('../assets/images/products/pain-frai/tortilla-maxi.png'),
  '1/tortilla-30cm-18pcs': require('../assets/images/products/pain-frai/tortilla-30cm-18pcs.png'),
  '1/tortilla-30-complet': require('../assets/images/products/pain-frai/tortilla-30-complet.png'),
  '1/fond-de-tarte-sucre': require('../assets/images/products/pain-frai/fond-de-tarte-sucre.png'),
  '1/fond-de-tarte-sale': require('../assets/images/products/pain-frai/fond-de-tarte-sale.png'),
  '3/pain-semoule-pm-45g': require('../assets/images/products/pain-surgele/pain-semoule-pm-45g.jpg'),
  '3/pain-complet-pm-45g': require('../assets/images/products/pain-surgele/pain-complet-pm-45g.jpg'),
  '3/pain-complet-gm220g': require('../assets/images/products/pain-surgele/pain-complet-gm220g.jpg'),
  '3/pain-orge-gm225': require('../assets/images/products/pain-surgele/pain-orge-gm224.jpg'),
  '3/pain-orge-pm-45': require('../assets/images/products/pain-surgele/pain-orge-pm-45.jpg'),
  '3/pain-rond-economique-210g': require('../assets/images/products/pain-surgele/pain-rond-economique-210g.jpg'),
  '3/pain-compagne-seigle-400g': require('../assets/images/products/pain-surgele/pain-compagne-seigle-400g.jpg'),
  '1/pain-de-mie-maxi-complet': require('../assets/images/products/pain-frai/pain-de-mie-maxi-complet.png'),
  '2/brownies': require('../assets/images/products/gateaux-et-patisserie/brownies.jpg'),
  '2/cheese-cake-citron': require('../assets/images/products/gateaux-et-patisserie/cheese-cake-citron.jpg'),
  '2/cheese-cake-fruits-rouges': require('../assets/images/products/gateaux-et-patisserie/cheese-cake-fruits-rouges.jpg'),
  '2/muffins-aux-amandes': require('../assets/images/products/gateaux-et-patisserie/muffins-aux-amandes.jpg'),
  '2/muffins-aux-fruits-rouges': require('../assets/images/products/gateaux-et-patisserie/muffins-aux-fruits-rouges.jpg'),
  '2/muffins-chocolat': require('../assets/images/products/gateaux-et-patisserie/muffins-chocolat.jpg'),
  '2/muffins-chocolat-fourrage-nutolade': require('../assets/images/products/gateaux-et-patisserie/muffins-chocolat-fourrage-nutolade.jpg'),
  '2/muffins-maxi-chocolat': require('../assets/images/products/gateaux-et-patisserie/muffins-maxi-chocolat.jpg'),
  '2/muffins-vanille': require('../assets/images/products/gateaux-et-patisserie/muffins-vanille.jpg'),
  '2/muffins-nature': require('../assets/images/products/gateaux-et-patisserie/muffins-nature.jpg'),
  '2/tarte-citron': require('../assets/images/products/gateaux-et-patisserie/tarte-citron.jpg'),
  '2/tarte-chocolat': require('../assets/images/products/gateaux-et-patisserie/tarte-chocolat.jpg'),
  '2/tarte-fraise': require('../assets/images/products/gateaux-et-patisserie/tarte-fraise.jpg'),
  '2/tarte-framboise': require('../assets/images/products/gateaux-et-patisserie/tarte-framboise.jpg'),
  '2/tarte-abricot': require('../assets/images/products/gateaux-et-patisserie/tarte-abricot.jpg'),
  '2/tarte-mangue': require('../assets/images/products/gateaux-et-patisserie/tarte-mangue.jpg'),
  '2/mille-feuille-caramel': require('../assets/images/products/gateaux-et-patisserie/mille-feuille-caramel.jpg'),
  '2/mille-feuille-vanille': require('../assets/images/products/gateaux-et-patisserie/mille-feuille-vanille.jpg'),
  '2/opera': require('../assets/images/products/gateaux-et-patisserie/opera.jpg'),
  '2/royal': require('../assets/images/products/gateaux-et-patisserie/royal.jpg'),
  '2/foret-noire': require('../assets/images/products/gateaux-et-patisserie/foret-noire.jpg'),
  // '2/pf-macaron-cafe': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-cafe.jpg'),
  // '2/pf-macaron-caramel-sesame': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-caramel-sesame.jpg'),
  // '2/pf-macaron-chocolat': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-chocolat.jpg'),
  // '2/pf-macaron-citron': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-citron.jpg'),
  // '2/pf-macaron-citron-moelleux': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-citron-moelleux.jpg'),
  // '2/pf-macaron-citron-vert-basilic': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-citron-vert-basilic.jpg'),
  // '2/pf-macaron-framboise-moelleux': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-framboise-moelleux.jpg'),
  // '2/pf-macaron-framboise': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-framboise.jpg'),
  // '2/pf-macaron-framboise-ind': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-framboise-ind.jpg'),
  // '2/pf-macaron-gingembre': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-gingembre.jpg'),
  // '2/pf-macaron-pistache': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-pistache.jpg'),
  // '2/pf-macaron-vanille': require('../assets/images/products/gateaux-et-patisserie/pf-macaron-vanille.jpg'),
  '3/baguette-tradition-olive-gm': require('../assets/images/products/pain-surgele/baguette-tradition-olive-gm.jpg'),
  '3/baguette-tradition-pavot': require('../assets/images/products/pain-surgele/baguette-tradition-pavot.jpg'),
  '3/baguette-tradition-sesame': require('../assets/images/products/pain-surgele/baguette-tradition-sesame.jpg'),
  '3/baguette-tradition-multi-cereales': require('../assets/images/products/pain-surgele/baguette-tradition-multi-cereales.jpg'),
  '3/baguette-economique': require('../assets/images/products/pain-surgele/baguette-economique.jpg'),
  '3/flute-complete': require('../assets/images/products/pain-surgele/flute-complete.jpg'),
  '3/baguette-a-lancienne-nature': require('../assets/images/products/pain-surgele/baguette-a-lancienne-nature.jpg'),
  '3/baguette-semoule': require('../assets/images/products/pain-surgele/baguette-semoule.png'),
  '3/pistolet-nature-50g': require('../assets/images/products/pain-surgele/pistolet-nature-50g.jpg'),
  '3/pistolet-olive-50g': require('../assets/images/products/pain-surgele/pistolet-olive-50g.jpg'),
  // '3/pistolet-complet-50g': require('../assets/images/products/pain-surgele/pistolet-complet-50g.jpg'),
  '3/pistolet-pavot-50g': require('../assets/images/products/pain-surgele/pistolet-pavot-50g.jpg'),
  '3/pistolet-sesam-50g': require('../assets/images/products/pain-surgele/pistolet-sesam-50g.jpg'),
  '3/baguetine-60g': require('../assets/images/products/pain-surgele/baguetine-60g.jpg'),
  '4/mini-pain-choco': require('../assets/images/products/viennoiserie/mini-pain-choco.png'),
  '4/mini-croissant': require('../assets/images/products/viennoiserie/mini-croissant.png'),
  '4/mini-torsade': require('../assets/images/products/viennoiserie/mini-torsade.png'),
  '4/pain-choco-110g': require('../assets/images/products/viennoiserie/pain-choco-110g.png'),
  '4/chausson-aux-pommes-100g': require('../assets/images/products/viennoiserie/chausson-aux-pommes-100g.png'),
  '4/croissant-70g': require('../assets/images/products/viennoiserie/croissant-70g.png'),
  '4/pain-suisse-chocolat-100g': require('../assets/images/products/viennoiserie/pain-suisse-chocolat-100g.png'),
  '1/pain-de-mie-maxi-nature': require('../assets/images/products/pain-frai/pain-de-mie-maxi-nature.png'),
  '1/pain-pavot': require('../assets/images/products/pain-frai/pain-pavot.png'),
  '1/pain-de-mie-complet-sans-sel': require('../assets/images/products/pain-frai/pain-de-mie-complet-sans-sel.png'),
  '1/pain-de-mie-integral': require('../assets/images/products/pain-frai/pain-de-mie-integral.png'),
  '3/baguette-complete': require('../assets/images/products/pain-surgele/baguette-complete.jpg'),
  '4/pain-raisin': require('../assets/images/products/viennoiserie/pain-raisin.png'),
  '4/mini-pain-raisin': require('../assets/images/products/viennoiserie/mini-pain-raisin.png'),
};
